name: Baballe Jaji Backend

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            PROJECT_DIR="${{ secrets.PROJECT_PATH }}"
            REPO_URL="https://${{ secrets.VPS_USER }}:${{ secrets.REPO_PATH }}@github.com/nubixlabs/baballejaji-limited-backend.git"
            cd $PROJECT_DIR
            sudo chown -R ${{ secrets.VPS_USER }}:${{ secrets.VPS_USER }} $PROJECT_DIR
            git config --global --add safe.directory $PROJECT_DIR
            git remote set-url origin $REPO_URL
            git pull origin main
            